import 'dart:io';

import '../data/prompt_store.dart';
import '../models/prompt_item.dart';

class ProjectPromptWriter {
  Future<List<ProjectPromptWriteResult>> writeEnabledPrompts({
    required PromptStore store,
    required AgentProject project,
  }) async {
    final results = <ProjectPromptWriteResult>[];

    for (final agent in AgentRuntime.values) {
      final prompts = store.enabledPromptsFor(project.id, agent);
      final target = targetFile(project, agent);
      final block = _renderManagedBlock(project, agent, prompts);
      final existing = await target.exists() ? await target.readAsString() : '';
      await target.writeAsString(_mergeManagedBlock(existing, block));
      results.add(
        ProjectPromptWriteResult(
          agent: agent,
          path: target.path,
          promptCount: prompts.length,
        ),
      );
    }

    return results;
  }

  File targetFile(AgentProject project, AgentRuntime agent) {
    return File('${project.path}${Platform.pathSeparator}${_fileName(agent)}');
  }

  String _fileName(AgentRuntime agent) {
    switch (agent) {
      case AgentRuntime.codex:
        return 'AGENTS.md';
      case AgentRuntime.gemini:
        return 'GEMINI.md';
      case AgentRuntime.claude:
        return 'CLAUDE.md';
    }
  }

  String _renderManagedBlock(
    AgentProject project,
    AgentRuntime agent,
    List<PromptItem> prompts,
  ) {
    final buffer = StringBuffer()
      ..writeln('<!-- agent-manager:start -->')
      ..writeln('## ${agent.label} prompts')
      ..writeln()
      ..writeln('Project: ${project.name}')
      ..writeln('Generated by Agent Manager.')
      ..writeln();

    if (prompts.isEmpty) {
      buffer
        ..writeln('No enabled prompts for ${agent.label}.')
        ..writeln()
        ..writeln('<!-- agent-manager:end -->')
        ..writeln();
      return buffer.toString();
    }

    for (final prompt in prompts) {
      buffer
        ..writeln('## ${prompt.title}')
        ..writeln()
        ..writeln('- Kind: ${prompt.kind.label}')
        ..writeln('- Scope: ${prompt.scope.label}')
        ..writeln()
        ..writeln(prompt.content)
        ..writeln();
    }

    buffer.writeln('<!-- agent-manager:end -->');
    buffer.writeln();
    return buffer.toString();
  }

  String _mergeManagedBlock(String existing, String block) {
    const start = '<!-- agent-manager:start -->';
    const end = '<!-- agent-manager:end -->';

    final startIndex = existing.indexOf(start);
    final endIndex = existing.indexOf(end);

    if (startIndex == -1 || endIndex == -1 || endIndex < startIndex) {
      final prefix = existing.trimRight();
      return prefix.isEmpty ? block : '$prefix\n\n$block';
    }

    final before = existing.substring(0, startIndex).trimRight();
    final after = existing.substring(endIndex + end.length).trimLeft();
    final merged = StringBuffer();

    if (before.isNotEmpty) {
      merged
        ..writeln(before)
        ..writeln();
    }

    merged.write(block.trimRight());

    if (after.isNotEmpty) {
      merged
        ..writeln()
        ..writeln()
        ..write(after);
    } else {
      merged.writeln();
    }

    return merged.toString();
  }
}

class ProjectPromptWriteResult {
  const ProjectPromptWriteResult({
    required this.agent,
    required this.path,
    required this.promptCount,
  });

  final AgentRuntime agent;
  final String path;
  final int promptCount;
}
